### ISSUE TITLE
启用和禁用包时会有如下错误。

### ISSUE THREAD

**Issue by mikuyourworld** [PerfBleu/portune2#2]
![QQ图片20220928130454](https://user-images.githubusercontent.com/30253025/192685253-fb9f81f7-a778-437c-bbbe-76d26d446f57.png)
![QQ图片20220928130452](https://user-images.githubusercontent.com/30253025/192685254-76f5cba3-f5af-4b55-89cc-317b658c070a.png)
看起来像是config那里有什么问题

**Comment by mikuyourworld** [comment]
好像是因为初始化不会往config.ini加入东西 导致读不到值 手动加了就ok了

**Comment by PerfBleu** [comment]
安装好之后抽一次签就自动初始化了，直接启用禁用是不会初始化的。
最近忙，已有有时间改一下逻辑。

**Comment by mikuyourworld** [comment]
原来如此，谢谢大佬。
