### ISSUE TITLE
插件无法加入bot

### ISSUE THREAD

**Issue by 15220526** [PerfBleu/portune2#3]
已经在bot.py里加入文件名了但是没有正确被导入，
![image](https://user-images.githubusercontent.com/106159640/198494863-f20f4fbd-1b3a-49d4-90a6-3b00efb79652.png)
输入帮助也没有显示该插件的存在
![image](https://user-images.githubusercontent.com/106159640/198495076-e57e4efa-20e0-4578-b87b-bbaeb27311e8.png)

**Comment by PerfBleu** [comment]
能看一下启动时的报错吗

> 已经在bot.py里加入文件名了但是没有正确被导入， ![image](https://user-images.githubusercontent.com/106159640/198494863-f20f4fbd-1b3a-49d4-90a6-3b00efb79652.png) 输入帮助也没有显示该插件的存在 ![image](https://user-images.githubusercontent.com/106159640/198495076-e57e4efa-20e0-4578-b87b-bbaeb27311e8.png)

**Comment by 15220526** [comment]
哦忘了截图启动的时候截图了不好意思，这个是启动报错截图
![image](https://user-images.githubusercontent.com/106159640/198495903-34c6145f-0d80-41bf-8a26-463d167bcbfa.png)

**Comment by PerfBleu** [comment]
知道了，马上改（

**Comment by PerfBleu** [comment]
> 哦忘了截图启动的时候截图了不好意思，这个是启动报错截图 ![image](https://user-images.githubusercontent.com/106159640/198495903-34c6145f-0d80-41bf-8a26-463d167bcbfa.png)

更新一下试试吧

**Comment by 15220526** [comment]
可以运行了，幸苦了捏
